### ISSUE TITLE
Flush-left not working properly with JSON

### ISSUE THREAD

**Issue by mightyCelu** [chilicuil/vim-sprunge#14]
Hi,
the flush-left implementation (which worked well for me so far!) seems to have trouble with JSON.
As an example I used the [json.org/example](http://www.json.org/example) object:
```
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
```
From which the 'GlossEntry'-Object gets pasted like [this](http://sprunge.us/IRLH):
```
"GlossEntry": {
    "ID": "SGML",
SGML",
: "Standard Generalized Markup Language",
"SGML",
ISO 8879:1986",
 {
        "para": "A meta-markup language, used to create markup languages such as DocBook.",
lso": ["GML", "XML"]
    },
 "markup"
}
```

**Comment by chilicuil** [comment]
Hello,

It doesn't seems to be Json specific, the linked text has a mix of tabs and spaces  which confuses `indent()`, I'm not sure how to workaround it, so I've added an option `g:sprunge_tabs2spaces` to normalize the file before indenting it. This options is disabled by default because the current implementation is slow with big files, you can indent manually your files (selecting the desired text and pressing '=' in vim) before executing vim-sprunge or use the new option.

Let me know if you find any drawbacks.

Bests

**Comment by mightyCelu** [comment]
Thanks for the fix, I forgot to reply to it. I tried it and it worked. In practice I now got used to using the indenting hotkey you posted though, so I cant didnt use it alot.
